create table if not exists users (
    id bigint generated by default as identity not null,
    name varchar(100) not null,
    surname varchar(100) not null,
    email varchar(250) not null,
    team_id bigint
);

create table if not exists teams (
    id bigint generated by default as identity not null,
    name varchar(250) not null
);
